// Follow closely with src/rendering/translator.rs
struct Vertex {
  @location(0) pos: vec3f,
  @location(1) tex_coord: vec2f
}

struct VertexOutput {
  @builtin(position) result_pos: vec4f,
  @location(0) tex_coord: vec2f
}

struct Uniforms {
  // The width and height of the output
  // in window
  output_width: f32,
  output_height: f32,
  
  // The width and height of game
  // viewport
  render_width: f32,
  render_height: f32,
}

@group(0) @binding(2) var<uniform> uniforms: Uniforms;

@vertex
fn vs_main(
  input: Vertex,
  @builtin(instance_index) index: u32
) -> VertexOutput {
  var out: VertexOutput;
  out.result_pos = vec4(input.pos, 1.0);
  out.tex_coord = input.tex_coord;
  
  let output_aspect = uniforms.output_width / uniforms.output_height;
  let render_aspect = uniforms.render_width / uniforms.render_height;

  // AI slop generated by Gemini
  if output_aspect > render_aspect {
    out.result_pos.x *= render_aspect / output_aspect;
  } else {
    out.result_pos.y *= output_aspect / render_aspect;
  }

  return out;
}

@group(0) @binding(0)
var frame_sampler: sampler;

@group(0) @binding(1)
var input_frame: texture_2d<f32>;

struct FragmentInput {
  @location(0) tex_coord: vec2f
}

@fragment
fn fs_main(
  input: FragmentInput
) -> @location(0) vec4f {
  return textureSample(input_frame, frame_sampler, input.tex_coord);
}


